### ISSUE TITLE
InMemoryRequestHandler processAddRequest cannot add entry, when its DN is not on any baseDNs

### ISSUE THREAD

**Issue by liptga** [pingidentity/ldapsdk#64]
Hi,

I am new to LDAP, so please be patient if I write or ask something wrong. I want to use the in memory LDAP server to test Spring Data LDAP repositories without the need of a real server. I use the server through [embedded-ldap-junit rule](https://github.com/zapodot/embedded-ldap-junit).

I want to populate the server using an LDIF file:

> version: 1
> 
> dn: DC=local

The BaseDN is defined like this: DC=yyy,DC=xxx,DC=local.

Consider this code part from [InMemoryRequestHandler.processAddRequest(final int messageID, final AddRequestProtocolOp request, final List<Control> controls)](https://github.com/pingidentity/ldapsdk/blob/2bd50f47acce1212115851a15961581dcd2c4844/src/com/unboundid/ldap/listener/InMemoryRequestHandler.java):

```java
// See if the entry DN is one of the defined base DNs.  If so, then we can
// add the entry.
if (baseDNs.contains(dn))
{
	entryMap.put(dn, new ReadOnlyEntry(entry));
	indexAdd(entry);
	addChangeLogEntry(request, authzDN);
	return new LDAPMessage(messageID,
		 new AddResponseProtocolOp(ResultCode.SUCCESS_INT_VALUE, null, null,
			  null),
		 responseControls);
}

// See if the parent entry exists.  If so, then we can add the entry.
final DN parentDN = dn.getParent();
if ((parentDN != null) && entryMap.containsKey(parentDN))
{
	entryMap.put(dn, new ReadOnlyEntry(entry));
	indexAdd(entry);
	addChangeLogEntry(request, authzDN);
	return new LDAPMessage(messageID,
		 new AddResponseProtocolOp(ResultCode.SUCCESS_INT_VALUE, null, null,
			  null),
		 responseControls);
}

// The add attempt must fail.
return new LDAPMessage(messageID, new AddResponseProtocolOp(
   ResultCode.NO_SUCH_OBJECT_INT_VALUE, getMatchedDNString(dn),
   ERR_MEM_HANDLER_ADD_MISSING_PARENT.get(request.getDN(),
		dn.getParentString()),
   null));
```

So it seems that a root (top level) entry cannot be added, since it is not on the baseDN. This case I get an exception like this:

    java.lang.IllegalStateException: Can not initiate in-memory LDAP server due to an exception
    	at org.zapodot.junit.ldap.internal.EmbeddedLdapRuleImpl.createForConfiguration(EmbeddedLdapRuleImpl.java:53)
    	at org.zapodot.junit.ldap.EmbeddedLdapRuleBuilder.build(EmbeddedLdapRuleBuilder.java:174)
    	....
    	at org.junit.rules.RuleChain.apply(RuleChain.java:93)
    	at org.junit.rules.RunRules.applyAll(RunRules.java:26)
    	at org.junit.rules.RunRules.<init>(RunRules.java:15)
    	at org.junit.runners.BlockJUnit4ClassRunner.withTestRules(BlockJUnit4ClassRunner.java:400)
    	at org.junit.runners.BlockJUnit4ClassRunner.withRules(BlockJUnit4ClassRunner.java:356)
    	at org.junit.runners.BlockJUnit4ClassRunner.methodBlock(BlockJUnit4ClassRunner.java:278)
    	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
    	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
    	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
    	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
    	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
    	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
    	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
    	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
    	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:89)
    	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:41)
    	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:541)
    	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:763)
    	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:463)
    	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:209)
    Caused by: LDAPException(resultCode=32 (no such object), errorMessage='Unable to add entry 'DC=local' because its parent entry 'null' does not exist in the server.', ldapSDKVersion=4.0.10, revision=b2272901fd62ad978017ff1aeb049cafc1999b12)
    	at com.unboundid.ldap.listener.InMemoryRequestHandler.addEntry(InMemoryRequestHandler.java:4587)
    	at com.unboundid.ldap.listener.InMemoryRequestHandler.importFromLDIF(InMemoryRequestHandler.java:4408)
    	at com.unboundid.ldap.listener.InMemoryDirectoryServer.importFromLDIF(InMemoryDirectoryServer.java:1234)
    	at com.unboundid.ldap.listener.InMemoryDirectoryServer.importFromLDIF(InMemoryDirectoryServer.java:1206)
    	at org.zapodot.junit.ldap.internal.EmbeddedLdapRuleImpl.createServer(EmbeddedLdapRuleImpl.java:64)
    	at org.zapodot.junit.ldap.internal.EmbeddedLdapRuleImpl.createForConfiguration(EmbeddedLdapRuleImpl.java:50)
    	... 22 more

Please give me feedback, if this is a bug in your code, or I do use the server completely wrong. I do not understand completely why an entry without parent cannot be added.

Thanks,

Gábor Lipták

**Comment by dirmgr** [comment]
If I'm reading your summary correctly, you've created the in-memory directory server with a base DN of "DC=yyy,DC=xxx,DC=local", and you're trying to add the entry "DC=local". The server is rejecting that because you can't add an entry above the base DN. The base DN defines the topmost entry you're allowed to have in the server (or at least, that portion of the tree). If you want to have a "DC=local" entry, then you should make your base DN "DC=local".

I will say that the error message:

    Unable to add entry 'DC=local' because its parent entry 'null' does not exist in the server.

is not the best error message. I'll update the server to improve that. The updated message will probably be something like

    Unable to add entry 'DC=local' because it is not within any of the configured base DNs.

**Comment by liptga** [comment]
Ok, so it is intended. Thanks for the explanation. Changing the message is a good idea, since if I see a "null" in the message, that seems to be a bug. Thanks for your prompt response.

**Comment by dirmgr** [comment]
I just committed a change that improves the diagnostic message that the in-memory directory server returns if you try to add an entry that is not within any of the configured base DNs. It will be included in the next release, but you can get it now if you check out and build the LDAP SDK for yourself.

**Comment by liptga** [comment]
I have checked your changes, looks good to me. Thanks.

**Comment by jrichardsz** [comment]
For me the error was that java and ldif file were not relationated. This worked 

```
# note : dc=example,dc=com
InMemoryDirectoryServerConfig config = new InMemoryDirectoryServerConfig("dc=example,dc=com");
```

sample.ldif first line
```
dn: dc=example,dc=com
```
